{
 "title": "jMeter_Dashboard",
 "description": "Show response time, users, errors (jMeter)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"edata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min\" or r[\"_field\"] == \"pct90.0\" or r[\"_field\"] == \"pct95.0\" or r[\"_field\"] == \"pct99.0\" or r[\"_field\"] == \"hit\" or r[\"_field\"] == \"avg\")\r\n  |> filter(fn: (r) => r[\"application\"] == \"InfluxDB2\")\r\n  |> filter(fn: (r) => r[\"statut\"] == \"ok\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"edata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"startedT\" or r[\"_field\"] == \"hit\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"edata\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jmeter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"application\"] == \"InfluxDB2\")\r\n  |> filter(fn: (r) => r[\"responseMessage\"] == \"Non HTTP response message: Connect to edata.gov.ua:443 [edata.gov.ua/195.190.152.100] failed: Read timed out\" or r[\"responseMessage\"] == \"Non HTTP response message: Connect to openbudget.gov.ua:443 [openbudget.gov.ua/195.190.152.100] failed: Read timed out\" or r[\"responseMessage\"] == \"Non HTTP response message: Socket closed\" or r[\"responseMessage\"] == \"Non HTTP response message: openbudget.gov.ua:443 failed to respond\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}